name: Laravel CI

on: 
  workflow_dispatch:
    inputs:
      test:
        description: 'Run tests'
        required: true
        default: 'true'

#on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.2]

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          #php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Run script
        run: |
          echo "PHP VERSION ${{ matrix.php-version }}"
          php -v

      - name: Ensure storage and cache directories exist
        run: |
          mkdir -p storage/logs
          mkdir -p bootstrap/cache
          chmod -R 777 storage bootstrap/cache

      #- name: Update Composer dependencies
      #  id: composer-update
      #  run: composer update --with-all-dependencies

      - name: Install dependencies
        #if: steps.composer-update.outcome == 'success'
        run: composer install --no-interaction

      - name: Set App
        run: cp .env.example .env 

      - name: Clear Laravel caches
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear

      - name: Cache Laravel config
        run: php artisan config:cache      

      - name: Generate App Key
        run: php artisan key:generate

      - name: Run test
        run: vendor/bin/phpunit

      - name: deploy
        run: ls

      - name: Artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: laravel-tests
          path: storage/logs